print('MAD LIB THEATRE')
print("create your own Jimmy Fallon Mad Lib scene and act it out with your family and friends!")
a= input("Male Name:")
b= input("Name of your favorite teacher:")
c= input('Exclamation:')
d= input('Number:')
e= input('Plural Objects:')
f= input('Store Name:')
g= input('Body Part:')
h= input('Silly Word:')
i= input('Name of Holiday:')
j= input('Celebrity Name:')
k= input('Movie Title:')
l= input('Verb Ending in -Ing:')
m= input('Amount of Distance:')
n= input('Country:')
o= input('Object:')
p= input('Occupation:')
q= input('Animal:')
r= input("Famous Movie Quote:")
s= input("Body Part:")
t= input("Children’s Song:")
u= input("Adjective:")
SCENE= f'DETECTIVE: Hello. I’m Detective {a}. And, you are…\nSUSPECT: {b}\nDETECTIVE: You are here today under suspicion of second degree robbery.\nSUSPECT: {c}!\n  DETECTIVE That’s right. {d} {e} were stolen from {f} and the crime scene has your {g} written ALL over it.\nSUSPECT: That is {h}.\nDETECTIVE: Where were you on the night of {i}?\nSUSPECT: I was with {j}. We were watching the movie {k}.\nDETECTIVE: Then why does security camera footage show you {l} just {m} away from the crime scene?\nSUSPECT: That’s a coincidence.\nDETECTIVE: Alright, I’m through playing games. Where are you from?\nSUSPECT: {n}.\nDETECTIVE: What did your parents do for a living?\nSUSPECT: My father was a {o} salesman and my mother was a {p}.\nDETECTIVE: Did they teach you to steal?\nSUSPECT: No. I told you didn’t do it!\nDETECTIVE: That’s enough! One of the best parts about being a detective is that I get to lock up criminals like you, and go home to my children and my pet {q} and say, {r}.\nSUSPECT: Fine, I did it. I committed the robbery. But I only did it because I needed the money to buy myself {s} implants.\nDETECTIVE: I knew it all along. And every time I solve a crime, I sing my favorite song, {t}\n(sing song)\nSUSPECT: You have a {u} voice.\n(BEAT)\nAnd scene!'
print(SCENE)
