print("Are you ready to build your very own Mad Lib Script?")
print('type "yay" to start the game!')
yn=str(input())
if yn=='yay':
  print("let us start with choosing the theme of your interest!")
  print('1.Christmas Theif\n2.Detective Detective\n3.Worst Breakup Ever!')
answer= input('Type the Theme Number you would like to start with:')
if answer=='1':
  print('MAD LIB THEATRE')
  print("create your own Jimmy Fallon Mad Lib scene and act it out with your family and friends!")
  a= input("Type of Dessert:")
  b= input("Silly Word:")
  c= input('Another Word for Father:')
  d= input('Year:')
  e= input('Celebrity Name:')
  f= input('Type of Plant:')
  g= input('Adjective:')
  h= input('Something You’d Name a Pet:')
  i= input('Name of a Band:')
  j= input('Plural Animal:')
  k= input('Verb Ending in -Ing:')
  l= input('Number:')
  m= input('Measurement of Time:')
  n= input('Body Part:')
  o= input('Type of Beer:')
  p= input('Type of Doctor:')
  q= input('One Syllable Noise:')
  r= input('Plural Noun:')
  s= input("Mode of Transportation:")
  t= input("Holiday:")
  print('--------------------')
  SCENE= f'ELF: Hi Santa.\nSANTA: Hello {a}.\nELF: You’re looking at me like I’m on your naughty list.\nSANTA: I was counting my toys and was one {b} short. I believe you stole it.\nELF: But {c}!\nSANTA: I started making that toy in {d}. What will little {e} think when he/she wakes up on Christmas morning with nothing under the {f}?\nELF: I would never steal such a {g} toy.\nSANTA: Where were you the night before Christmas?\nELF: I was with {h}. We were listening to {i}’s holiday album and making snow {j}.\nSANTA: Then why did Rudolph see you {k} on the roof {l} {m} before the toy went missing?\nELF: That’s a coincidence.\nSANTA: The reason I work so hard, is because I get to spread joy to millions of people, and go sit by the fire shaking my {n} while eating cookies and drinking {o}.\nELF: Fine, I stole the toy. But I only did it because I wanted to impress my {p}.\nSANTA: {q},{q},{q} Every time there’s a holiday miracle, I sing my favorite Christmas song, Jingle {r}.\n(singing)\nJingle {r}, Jingle {r},\nJingle all the way.\nOh what fun it is to ride\nIn a one horse open {s}.\nELF Merry {t} Santa!\n(BEAT)\nAnd scene!'
  print(SCENE)
elif answer=='2':
  print('MAD LIB THEATRE')
  print("create your own Jimmy Fallon Mad Lib scene and act it out with your family and friends!")
  a= input("Male Name:")
  b= input("Name of your favorite teacher:")
  c= input('Exclamation:')
  d= input('Number:')
  e= input('Plural Objects:')
  f= input('Store Name:')
  g= input('Body Part:')
  h= input('Silly Word:')
  i= input('Name of Holiday:')
  j= input('Celebrity Name:')
  k= input('Movie Title:')
  l= input('Verb Ending in -Ing:')
  m= input('Amount of Distance:')
  n= input('Country:')
  o= input('Object:')
  p= input('Occupation:')
  q= input('Animal:')
  r= input("Famous Movie Quote:")
  s= input("Body Part:")
  t= input("Children’s Song:")
  u= input("Adjective:")
  print("--------------------")
  SCENE= f'DETECTIVE: Hello. I’m Detective {a}. And, you are…\nSUSPECT: {b}\nDETECTIVE: You are here today under suspicion of second degree robbery.\nSUSPECT: {c}!\n  DETECTIVE That’s right. {d} {e} were stolen from {f} and the crime scene has your {g} written ALL over it.\nSUSPECT: That is {h}.\nDETECTIVE: Where were you on the night of {i}?\nSUSPECT: I was with {j}. We were watching the movie {k}.\nDETECTIVE: Then why does security camera footage show you {l} just {m} away from the crime scene?\nSUSPECT: That’s a coincidence.\nDETECTIVE: Alright, I’m through playing games. Where are you from?\nSUSPECT: {n}.\nDETECTIVE: What did your parents do for a living?\nSUSPECT: My father was a {o} salesman and my mother was a {p}.\nDETECTIVE: Did they teach you to steal?\nSUSPECT: No. I told you didn’t do it!\nDETECTIVE: That’s enough! One of the best parts about being a detective is that I get to lock up criminals like you, and go home to my children and my pet {q} and say, {r}.\nSUSPECT: Fine, I did it. I committed the robbery. But I only did it because I needed the money to buy myself {s} implants.\nDETECTIVE: I knew it all along. And every time I solve a crime, I sing my favorite song, {t}\n(sing song)\nSUSPECT: You have a {u} voice.\n(BEAT)\nAnd scene!'
  print(SCENE)
elif answer=='3':
  print('MAD LIB THEATRE')
  print("create your own Jimmy Fallon Mad Lib scene and act it out with your family and friends!")
  a= input("Number:")
  b= input("Male Name:")
  c= input('A pet name for a Rabbit:')
  d= input('An Adjective:')
  e= input('What you would shout if your dentist told you,"You have six cavities":')
  f= input('Amount of Time:')
  g= input('What a bartender would say to customers when the bar is closing:')
  h= input('Historical Event:')
  i= input('Adjective to describe a Fish:')
  j= input('Body Part:')
  k= input('Plural Occupations:')
  l= input('Plural Animals:')
  m= input('Verb ending in -ing:')
  n= input('Celebrity Name:')
  o= input('Plural type of Food:')
  p= input('Character from "Friends":')
  q= input('Insult a kid would say:')
  r= input('Another insult a kid would say:')
  s= input("One more insult a kid would say, then I'm done:")
  t= input("Plural object:")
  u= input("Verb:")
  v= input("Another body Part:")
  w= input("Verb:")
  x= input("Cartoon Character:")
  y= input("Verb ending in -ing:")
  print("--------------------")
  
  SCENE= f'[Birds chirping]\nHim:Really is a beautiful day to go apple picking. This is the most fun I have had in {a} years.\nHer:Listen, {b}, I have been thinking, and we need to talk.\nHim:What is it, {c}?\nHer:What I am about to say might be {d} to hear, but here it goes...I think we should break up.\nHim:{e}\nHer:I am so sorry.We have shared so much over the past {f}, but…{g}..\nHim:That\'s cold!\nHow long have you have been feeling this way?\nHer:Since the {h}\nHim:I can\'t believe this.\nIs this because of my {i} {j}?\nHer:No, no, it is not. We’re just -- We are just really different people.\nI was brought up by two {k} and you were raised by {l}. I enjoy going out, and come home every night to find you {m} on the couch, watching YouTube videos of {n} eating {o}.\nHim: I understand. Well, I have something to tell you, too, that is not easy to admit. I have been cheating on you with {p} from "Friends".\nHer:{q}\nHim:{r}\nHer:{s}\nHer:Hey! I am taking the {t} and moving out.\nHim:Hey! Hey, please don’t {u}. That is a term that my {l} parents used to say. I hate seeing you do that, so just have a seat here. I am sorry things did not work out.\nHer:I am, too. I will always have a special place for you in my {v}\nHim:It is during times like this, I like for us to recite our favourite love quote.\nBoth:"You got to {w} like {x} is watching, and you got to love like there is nobody {y}"\nAnd scene!'
  print(SCENE)