print('MAD LIB THEATRE')
print("create your own Jimmy Fallon Mad Lib scene and act it out with your family and friends!")
a= input("Number:")
b= input("Male Name:")
c= input('A pet name for a Rabbit:')
d= input('An Adjective:')
e= input('What you would shout if your dentist told you,"You have six cavities":')
f= input('Amount of Time:')
g= input('What a bartender would say to customers when the bar is closing:')
h= input('Historical Event:')
i= input('Adjective to describe a Fish:')
j= input('Body Part:')
k= input('Plural Occupations')
l= input('Plural Animals:')
m= input('Verb ending in -ing:')
n= input('Celebrity Name:')
o= input('Plural type of Food:')
p= input('Character from "Friends":')
q= input('Insult a kid would say:')
r= input('Another insult a kid would say:')
s= input("One more insult a kid would say, then I'm done:")
t= input("Plural object:")
u= input("Verb:")
v= input("Another body Part:")
w= input("Verb:")
x= input("Cartoon Character:")
y= input("Verb ending in -ing:")

SCENE= f'[Birds chirping]\nHim:Really is a beautiful day to go apple picking. This is the most fun I have had in {a} years.\nHer:Listen, {b}, I have been thinking, and we need to talk.\nHim:What is it, {c}?\nHer:What I am about to say might be {d} to hear, but here it goes...I think we should break up.\nHim:{e}\nHer:I am so sorry.We have shared so much over the past {f}, but…{g}..\nHim:That\'\s cold!\nHow long have you have been feeling this way?\nHer:Since the {h}\nHim:I can\'t believe this.\nIs this because of my {i} {j}?\nHer:No, no, it is not. We’re just -- We are just really different people.\nI was brought up by two {k} and you were raised by {l}. I enjoy going out, and come home every night to find you {m} on the couch, watching YouTube videos of {n} eating {o}.\nHim: I understand. Well, I have something to tell you, too, that is not easy to admit. I have been cheating on you with {p} from "Friends".\nHer:{q}\nHim:{r}\nHer:{s}\nHer:Hey! I am taking the {t} and moving out.\nHim:Hey! Hey, please don’t {u}. That is a term that my {l} parents used to say. I hate seeing you do that, so just have a seat here. I am sorry things did not work out.\nHer:I am, too. I will always have a special place for you in my {v}\nHim:It is during times like this, I like for us to recite our favourite love quote.\nBoth:"You got to {w} like {x} is watching, and you got to love like there is nobody {y}"\nAnd scene!'
print(SCENE)
